
```{r}
link='https://github.com/EvansDataScience/VisualAnalytics_2_tabularData/raw/master/data/eduwa.rda'

#getting the data TABLE from the file in the cloud:
load(file=url(link))
```

```{r}
# how many unique values
length(unique(eduwa$Reduced.Lunch))
```

```{r}
# barplot without ggplot
# NumDF = numbers of degrees of freedom 
library(questionr)
NumDf=freq(eduwa$Reduced.Lunch) 

NumDf=data.frame(variable=as.numeric(row.names(NumDf)),
                 NumDf,
                 row.names = NULL)
```

```{r}
#resultado
head(NumDf)
```

```{r}
# ----BAD_barplot, ----------------------------------------------
library(ggplot2)
base = ggplot(data=NumDf,aes(x=variable,y=n))
base + geom_bar(stat='identity')
```

```{r}
# ----summary, --------------------------------------------------
summary(eduwa$Reduced.Lunch)
```

```{r}
# ---------------------------------------------------------------
# standard deviation:
sd(eduwa$Reduced.Lunch,na.rm = T)
```

```{r}
# ---------------------------------------------------------------
# median absolute deviation:
mad(eduwa$Reduced.Lunch,na.rm = T)
```

```{r}
# ---------------------------------------------------------------
# asymmetry
library(DescTools)
Skew(eduwa$Reduced.Lunch,na.rm = T,conf.level = 0.95, ci.type = "bca",R=3000)
```

```{r}
# ---------------------------------------------------------------
# shape
#library(DescTools)
Kurt(eduwa$Reduced.Lunch,na.rm = T,conf.level = 0.95, ci.type = "bca",R=3000)
```

```{r}
# ----GGLikeBase,,fig.height=7-----------------------------------
#ggplot
base= ggplot(eduwa,aes(x = Reduced.Lunch))  
h1= base + geom_histogram(binwidth = 20) 
h1
```

```{r}
# ---------------------------------------------------------------
MEAN=summary(eduwa$Reduced.Lunch)[4]
h1+ geom_vline(xintercept = MEAN)
```

```{r}
base= ggplot(eduwa,aes(y = Reduced.Lunch))  
b1= base + geom_boxplot() 
b1 +coord_flip()
```

```{r}
# difference between q3 and q1:
theIQR=IQR(eduwa$Reduced.Lunch,na.rm = T)
```

```{r}
(upperT=summary(eduwa$Reduced.Lunch)[[5]] + theIQR*1.5)
```

```{r}
sum(eduwa$Reduced.Lunch>upperT,na.rm = T)
```

```{r}
someValues=as.vector(summary(eduwa$Reduced.Lunch)[-c(4,6,7)])
theTicks = round(c(someValues,upperT),0)
b2 = b1 +coord_flip()
b3 = b2 + geom_hline(yintercept = upperT, 
                color='grey8',linetype="dotted", size=2) 
b3 + scale_y_continuous(breaks = theTicks)
```

_______________________________________________________________________________
# Exercise 7 

```{r}
theVAR1=eduwa$Reduced.Lunch
theIQR=IQR(theVAR1,na.rm = T)
upperT=summary(eduwa$Reduced.Lunch)[[5]] + theIQR*1.5
aboves1=eduwa[which(theVAR1 > upperT),]
```

```{r}
## Show a boxplot for "Reduced Lunch"
base= ggplot(aboves1,aes(y = Reduced.Lunch))  
t1A= base + geom_boxplot(color='blue2') + coord_flip()
t1A
```

```{r}
##show a histogram for "Reduced Lunch"
base= ggplot(aboves1,aes(x = Reduced.Lunch))  
t1B= base + geom_histogram(binwidth = 4,color='blue',fill='blue') #changing width

t1B
```

```{r}
library(ggpubr)
```

```{r}
multid1_a = ggarrange(t1A,t1B,ncol = 1,nrow = 2)
multid3AN = annotate_figure(multid1_a,
                            top = text_grob("Visualizing Reduced Lunch",
                                            face = "bold", size = 12),
                            bottom = text_grob("Data source: EDUWA", 
                                               hjust = 1, x = 1,
                                               face = "italic", 
                                               size = 8),
                            left = "",
                            right = "")
multid3AN
```

